# Generated by Django 5.2.7 on 2025-10-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerservice',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='ownerservice',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
