# Generated by Django 5.2.7 on 2025-10-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=100)),
                ('unit_number', models.CharField(max_length=50)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
