# Generated by Django 5.2.7 on 2025-10-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='California', max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], default='Available', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='property_images/default.jpg', null=True, upload_to='property_images/')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
