# Generated by Django 5.2.7 on 2025-10-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_bathrooms_property_bedrooms_property_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='California', max_length=50),
        ),
    ]
