# Generated by Django 5.2.7 on 2025-10-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_available_property_city_property_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, default='property_images/default.jpg', null=True, upload_to='property_images/'),
        ),
    ]
