# Generated by Django 5.2.7 on 2025-10-28 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tenant_name',
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
