# Generated by Django 5.2.7 on 2025-10-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_tenant_name_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
